version: '3.9'

services:
  mongo:
    image: docker.xuanyuan.me/library/mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"  # 映射宿主机端口
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: tododb
    volumes:
      - mongo_data:/data/db  # 数据持久化

volumes:
  mongo_data:
